const fs = require('fs');
const axios = require('axios');

const ANTHROPIC_API_KEY = process.env.ANTHROPIC_API_KEY;

async function analyzeWithClaude() {
  try {
    // Read the PR diff
    const diff = fs.readFileSync('pr.diff', 'utf8');

    // Prepare the prompt
    const prompt = `You are an expert code reviewer. Analyze the following pull request diff and provide:
1. Security concerns (if any)
2. Performance issues (if any)
3. Code quality suggestions
4. Best practices recommendations
5. Overall assessment

Keep the review concise and actionable.

DIFF:
\`\`\`
${diff}
\`\`\`

Provide your review in a clear, structured format.`;

    // Call Claude API
    const response = await axios.post(
      'https://api.anthropic.com/v1/messages',
      {
        model: 'claude-3-5-sonnet-20241022',
        max_tokens: 1500,
        messages: [
          {
            role: 'user',
            content: prompt,
          },
        ],
      },
      {
        headers: {
          'x-api-key': ANTHROPIC_API_KEY,
          'anthropic-version': '2023-06-01',
          'content-type': 'application/json',
        },
      }
    );

    // Extract the review text
    const review = response.data.content[0].text;

    // Format as GitHub comment
    const formattedReview = `## 🤖 Claude AI Code Review

${review}

---
*This review was automatically generated by Claude AI.*`;

    // Save to file for the next step
    fs.writeFileSync('claude-review.md', formattedReview, 'utf8');
    console.log('Review generated successfully');
  } catch (error) {
    console.error('Error analyzing with Claude:', error.message);
    if (error.response) {
      console.error('API Response:', error.response.data);
    }
    process.exit(1);
  }
}

analyzeWithClaude();
